name: Deploy Hugo Site

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }} # 使用 PAT
          publish_dir: ./public
          publish_branch: gh-pages # 部署到 gh-pages
